name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    container: fedora:40
    permissions:
      contents: write # needed for uploading release artifact
    steps:
      - name: Install dependencies
        run: |
          sudo dnf upgrade --refresh -y
          sudo dnf install -y gcc gcc-c++ clang python3 make cmake meson git gh kernel-devel gtk4-devel libadwaita-devel poppler-glib-devel poppler-data alsa-lib-devel appstream-devel desktop-file-utils
      - name: Install toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add workspace as git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run cargo build
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rnote-thumbnailer
          path: target/release/rnote-thumbnailer
          if-no-files-found: error
      - name: Upload release asset
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} target/release/rnote-thumbnailer
